# version: "3"

# services:
#   postgres:
#     image: postgres
#     healthcheck:
#       test: psql postgres --command "select 1" -U postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: postgres

#   pact-broker:
#     image: pactfoundation/pact-broker:latest-multi
#     links:
#       - postgres
#     ports:
#       - 8000:9292
#     restart: always
#     environment:
#       PACT_BROKER_BASIC_AUTH_USERNAME: pact_workshop
#       PACT_BROKER_BASIC_AUTH_PASSWORD: pact_workshop
#       PACT_BROKER_DATABASE_USERNAME: postgres
#       PACT_BROKER_DATABASE_PASSWORD: password
#       PACT_BROKER_DATABASE_HOST: postgres
#       PACT_BROKER_DATABASE_NAME: postgres
#       PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "10"
#       PACT_BROKER_PUBLIC_HEARTBEAT: "true"

version: '3'
services:
  pact-verifier:
    # Build the Docker image from the Dockerfile in the current directory
    build: .
    # Set environment variables if needed
    environment:
      - LOG_LEVEL=TRACE
      - PACT_BROKER_URL=http://127.0.0.1:8000
      - PACT_BROKER_USERNAME=pact
      - PACT_BROKER_PASSWORD=pact
    # Expose the port that your application is running on
    ports:
      - "7071:7071"
